### ISSUE TITLE
[UNBLOCK] beacons3 at gvt2.com

### ISSUE THREAD

**Issue by azaceta** [arapurayil/aBL#11]
## Domain Name: 
_beacons3.gvt2.com_

## List Name: 
_General_

## Reason: 
_Other beacons 'X' are whitelisted, but I've observed this '3' one being blocked. I guess it's not possible using RegEx for unblocking so this one should be whitelisted too._

**Comment by arapurayil** [comment]
Thank you for reporting. Added to whitelist. Will be included in the next iteration.
