### ISSUE TITLE
[UNBLOCK] sucuri.net

### ISSUE THREAD

**Issue by iam-py-test** [arapurayil/aBL#13]
## Domain Name: <enter the domain name here>
`sucuri.net`

## List Name: <enter the list name here>
arapurayil's Block List (aBL) - Addon - NSFW, Porn, Gambling, Snuff 
## Reason: <enter the reason here>
This is a tool for scanning sites - it has no porn, no gambling, and no drugs. 
I am not sure why this domain is blocked, but the block prevents me from using it.

**Comment by arapurayil** [comment]
Thanks for reporting. You're right it shouldn't have been included. It was found in one of our source lists [Energized core - porn](https://raw.githubusercontent.com/AdroitAdorKhan/EnergizedProtection/master/core/hosts-porn).

I've included it in the whitelist and it'll be excluded in the subsequent iterations.
