### ISSUE TITLE
[UNBLOCK] https://pcsx4.com/

### ISSUE THREAD

**Issue by jenabaivab** [arapurayil/aBL#14]
## Domain Name: <enter the domain name here>
https://pcsx4.com/

## List Name: <enter the list name here>

Straight from your DNS, so I guess ABL General

## Reason: <enter the reason here>
PS4 emulator. Don't see why this is blocked.
P.S. - Are you no longer available on telegram?

**Comment by arapurayil** [comment]
Hi! The specified domain is not blocked on aBL. Its accessible on my DNS as well. I'm closing this issue now, feel free to reopen if you're facing this issue again.

**Comment by jenabaivab** [comment]
@arapurayil it's already unblocked by whichever list blocked it in the first place. Unblocked a couple of days after i reported it here.

**Comment by arapurayil** [comment]
Perhaps it was falsely blocked by one of the source lists. Anyway good to hear that it was resolved.

**Comment by jenabaivab** [comment]
@arapurayil did you drop off telegram completely?
