### ISSUE TITLE
[False Positive] Team logos not loading on nbastream.tv

### ISSUE THREAD

**Issue by jenabaivab** [arapurayil/aBL#3]
![image](https://user-images.githubusercontent.com/60446763/106419934-9e09d200-647f-11eb-8569-87b6cb2fb5de.png)

The logos are getting blocked for no reason, you can see it in the top bar.

**Comment by arapurayil** [comment]
Unblocked rolo.nocdnrlly.xyz. It should solve the issue.

**Comment by jenabaivab** [comment]
Yep, got it to work now. Thanks!

**Comment by jenabaivab** [comment]
@arapurayil it's weird, since the switch to ABL, I have been seeing some slowdowns throughout the last few days. Even YouTube videos sometimes take a while to start playing. Can't really pinpoint if it's because of the blocklists or something else changed.

**Comment by arapurayil** [comment]
@jenabaivab can you tell me which protocol you're using? Is it doh,dot,doq or dnscrypt?

**Comment by jenabaivab** [comment]
@arapurayil mostly on DoT, but also on DoH. The other day I was using DoH on windows, and tried downloading files from google drive and got capped at 4.5 MBps. Previously it was 10 MBps even with your DNS enabled. I switched to cloudflare DoH, and was back to 10 in a split second.

Regarding the slowdowns and slow video loading, it's mostly on android PrivateDNS.

**Comment by arapurayil** [comment]
@jenabaivab Is this happening outside of google services?

**Comment by jenabaivab** [comment]
Not really. I use Sync for Reddit on android, and there are slowdowns over there as well. Fetching posts, loading streamable videos, it's just weird performance in general.

**Comment by arapurayil** [comment]
I've switched to OISD on the DNS server for now. Kindly check if you're having slow downs now.

**Comment by jenabaivab** [comment]
@arapurayil it's better now but definitely not as snappy as say before 2 weeks. Reduced blocklists definitely helped though.

**Comment by arapurayil** [comment]
Less snapiness might be due to clearing of cache on my end. It'll improve over time. Are download speeds affected now?

**Comment by jenabaivab** [comment]
@arapurayil Download speeds have normalized as of now. Will inform if the lookup speed doesn't improve with time.

**Comment by arapurayil** [comment]
@jenabaivab Doing a little housekeeping. Have included more whitelists in aBL sources. Can you please check if the download speeds are affected now?

**Comment by jenabaivab** [comment]
@arapurayil seems to be okay now.

**Comment by jenabaivab** [comment]
@arapurayil any changes in sources? Slowdowns on youtube again. :/

**Comment by arapurayil** [comment]
@jenabaivab No. I don't think any 'good' google domain is blocked. The DNS server is also not overwhelmed by queries. The issue could be due to the low ttl time of *.googlevideo.com which is causing additional lookups. But even then, it should only cost a few ms. Anyway, I've made some changes in the server, but there is only so much one can do with unbound.
