### ISSUE TITLE
[UNBLOCK] tsukuba.wide.ad.jp

### ISSUE THREAD

**Issue by begundal** [arapurayil/aBL#7]
## Domain Name: tsukuba.wide.ad.jp
_propose only one domain at a time_

## List Name: General
_ex: General, Regional, Porn, etc_

## Reason: open source mirror
_explain in detail why you want this domain to be unblocked_

**Comment by begundal** [comment]
![Screenshot 2021-02-20 110420](https://user-images.githubusercontent.com/342539/108583559-c8f39180-736c-11eb-8321-e310cd857b2e.jpg)

**Comment by arapurayil** [comment]
Added to [unblock list](https://raw.githubusercontent.com/arapurayil/aBL_unblock/main/domains/main.txt).
Please use the new url: https://abl.arapurayil.com/filters/main.txt
